authEnabled: true

logging:
    level: INFO

http:
  port: 8443
  adminPort: 58443
  connectorType: nonblocking
  ssl:
      keyStore: ${ssl.cert.dir}/ssl.pfx
      keyStorePassword: zapp_pass
      keyStoreType:     pkcs12
  requestLog:
    console:
      enabled: false

webSocketConfiguration:
    maxTextMessageSize: 10485760

metricService:
    jobSize: 1000
    maxQueueSize: 2000000
    maxTimeBetweenRetries: 3000
    maxClientWaitTime: 60000
    tsdbWriterThreads: 1
    maxIdleTime: 10000
    maxConnectionBackOff: 5000
    minConnectionBackOff: 100
    bufferUpdateInterval: 100
    openTsdbClientPool:
      maxKeepAliveTime: 300000
      minTestTime:       60000
      clientBufferSize:  65536
      clients:
        - {host: localhost, port: 4242}
        - {host: localhost, port: 4242}
        - {host: localhost, port: 4242}
        - {host: localhost, port: 4242}

      clientFactory:
        keepAlive:          true
        connectTimeout:     1000
        soTimeout:          60000

managedReporter:
    metricReporters:
      - {posterType: http, username: "$env[CONTROLPLANE_CONSUMER_USERNAME]", password: "$env[CONTROLPLANE_CONSUMER_PASSWORD]", urlEnvironment: "CONTROLPLANE_CONSUMER_URL"}
      - {posterType: bean, beanName: metric-service-poster}

# tagWhiteList:
#   - my_allowed_tag
#   - my_other_allowed_tag
#
# tagWhiteListPrefixes:
#   - my_allowed_tag_prefix
#   - my_other_allowed_tag_prefix
